name: Validate
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  hacs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: hacs/action@main
        with:
          category: theme
  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: pip install yamllint
      - run: yamllint themes/
